[package]
name = "java-classfile-version"
version = "1.2.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["cargo"] }
thiserror = "2.0.12"
zip = { version = "2.6.1", default-features = false, features = [ "deflate-zlib" ] }
