[package]
name = "java-classfile-version"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.2"
tempfile = "3.19.1"
thiserror = "2.0.12"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
zip = "2.6.1"
